language: rust
rust: stable
cache: cargo
sudo: false
git:
  depth: 1

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:


addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - g++-5
      - c++-5

before_script:
  - |
      export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH &&
      ci/install-tools.sh
  - |
      which g++-5; which g++; export CXX=`which g++-5`;
  - |
      ci/install-glslangValidator.sh
script:
  - ci/run-all.sh
after_success:
  - ci/upload-docs.sh
