language: rust
rust: stable
cache: cargo
sudo: false
git:
  depth: 1
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - clang-3.9

before_script:
  - |
      export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH &&
      ci/install-tools.sh
  - |
      export CC=clang-3.9 CXX=clang++-3.9;
  - |
      ci/install-glslangValidator.sh
script:
  - ci/run-all.sh
after_success:
  - ci/upload-docs.sh
