language: rust
rust: stable
cache: cargo
sudo: false
git:
  depth: 1

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gcc-5
#       - libstdc++5

addons:
  apt:
    packages:
      - cmake
      - ninja-build

before_script:
  - |
      export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH &&
      ci/install-tools.sh
  - |
      ci/install-glslangValidator.sh
script:
  - ci/run-all.sh
after_success:
  - ci/upload-docs.sh
